configfile: "/home/kum03217/assignment-2-naveenkumartigs/workflow/config.yaml"

sample= config["samples"]

rule all:
    input:
        expand("../results/qc/fastqc/{sample}_R1_fastqc.html",
        sample=sample), 
        expand("../results/qc/fastqc/{sample}_R2_fastqc.html",
        sample=sample),

        #multiqc final file need to be kept here
        "../results/qc/multiqc_report.html",

        #to create sorted BAM files
        expand("../results/mapped2/{sample}.sorted.bam", 
        sample=sample),

        #indexed sorted bam files
        expand("../results/mapped2/{sample}.sorted.bam.bai", 
        sample=sample),

        #statistics files 
        expand("../results/stats/{sample}.flagstat.txt", 
        sample=sample)
#fastqc
rule navn_qc:
    input:
        r1="../data/fastq/{sample}_R1.fastq.gz",
        r2="../data/fastq/{sample}_R2.fastq.gz",
    output:
        r1="../results/qc/fastqc/{sample}_R1_fastqc.html",
        r2="../results/qc/fastqc/{sample}_R2_fastqc.html",
    shell:
        "fastqc {input.r1} {input.r2} -o ../results/qc/fastqc/"
#multiqc
rule navn_multi_qc:
    input:
        "../results/qc/fastqc/ecoli_k12_R1_fastqc.html",
        "../results/qc/fastqc/ecoli_k12_R2_fastqc.html",
    output:
        "../results/qc/multiqc_report.html"
    shell:
        "multiqc ../results/qc/fastqc -o ../results/qc/"

#reference genome index using bowtie2
rule navn_index:
    input:
        "../data/reference/ecoli_K12.fa"
    output:
        "../results/reference/ecoli_k12_index.1.bt2"
    params:
        prefix="../results/reference/ecoli_k12_index"
    shell:
        "bowtie2-build {input} {params.prefix}"
#mapping files to reference genome-using bowtie2
rule navn_map:
    input:
        idx="../results/reference/ecoli_k12_index.1.bt2",
        r1="../data/fastq/{sample}_R1.fastq.gz",
        r2="../data/fastq/{sample}_R2.fastq.gz",
    output:
        "../results/mapped2/{sample}.sam"
    params:
        idx_prefix="../results/reference/ecoli_k12_index"
    shell:
        "bowtie2 -x {params.idx_prefix} -1 {input.r1} -2 {input.r2} -p 8 -S {output}"

#convert files from sam to bam files
rule naven_sam_to_bam:
    input:
        "../results/mapped2/{sample}.sam"
    output:
        "../results/mapped2/{sample}.bam"
    shell:
        "samtools view -bS {input} > {output}"
    
#sorting bam files
rule navn_sort_bam:
    input:
        expand("../results/mapped2/{sample}.bam",
        sample=sample)
    output:
        expand("../results/mapped2/{sample}.sorted.bam",
        sample=sample)
    shell: 
        "samtools sort {input} -o {output}"

#indexing sorted bam files
rule navn_index_sorted_bam:
    input:
        expand("../results/mapped2/{sample}.sorted.bam",
        sample=sample)
    output: 
        expand("../results/mapped2/{sample}.sorted.bam.bai",
        sample=sample) 
    shell:
        "samtools index {input} {output}"

#mapping statistics
rule navn_map_stat:
    input:
        expand("../results/mapped2/{sample}.sorted.bam",
        sample=sample)
    output:
        expand("../results/stats/{sample}.flagstat.txt",
        sample=sample)
    shell:
        "samtools flagstat {input} > {output}"

##completed





    
